[project]
name = "agentd"
version = "0.1.0"
description = "agent daemon"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "appdirs>=1.4.4",
    "astra-assistants>=2.3.1",
]

[tool.uv.sources]
astra-assistants = { path = "../astra-assistants-api/client" }
